In [77]:
import numpy as np 

In [78]:
## 1d array ---  a single list of elements
## 2d array = [[]]  -- an array of arrays -- matrix --- row and columns 
## 3d array = [[[]]]    -- an array of 2d array 


In [79]:
## numpy creation array 
lst = list(range(1,31))
arr1 = np.array(lst)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [80]:
arr5 = np.array([1,2,3,4,5])
arr5

array([1, 2, 3, 4, 5])

In [81]:
arr2 = np.arange(1,31)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [82]:
## 2d array create 

In [83]:
arr3 = np.zeros((1,31))
arr3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [84]:
arr4 = np.ones((1,31))
arr4

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [85]:
arr6 = np.linspace(1,10,20)              #1-10 --> range,20 -- number of elements
arr6

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [86]:
arr7 = np.arange(1,31).reshape(5,6)           # one d array ko multidimensional array me creat ekarne ke
arr7

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [87]:
## random numbers array create karna 

arr8 = np.random.randint(1,100,10)       
arr8

array([60, 38, 70, 24, 98, 20, 87, 95, 32, 69])

In [88]:
arr9 = np.random.randint(1,5,(5,4))
arr9

array([[2, 4, 3, 2],
       [1, 3, 3, 3],
       [1, 2, 2, 2],
       [4, 2, 2, 1],
       [1, 3, 1, 4]])

In [89]:
arr10 = np.random.random(10)
arr10

array([0.95288552, 0.20093737, 0.86089561, 0.44372456, 0.95343031,
       0.96493319, 0.15407786, 0.68308926, 0.63373559, 0.27075513])

In [90]:
arr11 = np.random.random((5,2))
arr11

array([[0.47256732, 0.19087699],
       [0.05179499, 0.63129   ],
       [0.65903731, 0.72030827],
       [0.39860294, 0.9064095 ],
       [0.94475997, 0.74492223]])

In [91]:
### array attributes

arr12 = np.arange(60).reshape((12,5))
arr12

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [92]:
## shape mxn 

arr12.shape


(12, 5)

In [93]:
## data type

arr12.dtype

dtype('int32')

In [94]:
##dimension 

arr12.ndim

2

In [95]:
##size 

arr12.size

60

In [96]:
## convert multi dimensional array innto 1d array 

arr12.flatten()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [97]:
arr12.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [98]:
lst2d = [[1,2,3], [4,5,6]]

arr13 = np.array(lst2d)
arr13


array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
arr13.shape
##(rows, columns)

(2, 3)

In [100]:
##transpose --- shape ko ulta karna /// aapki matrix ko ulta karna

arr14 = arr13.T
arr14
arr14.shape


(3, 2)

In [101]:
##accessing elements 
#1d ----
# 2d 
#3d 


In [102]:
###1d -- [row start: row end:skip ]

In [103]:
arr15 = np.arange(60)
arr15

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [104]:
arr15[10]

10

In [105]:
arr15[15::2]

array([15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47,
       49, 51, 53, 55, 57, 59])

In [106]:
##2d ---matrix ---[row , col]---[Row start:row end:rowskip, col start:col end:skip]

In [107]:
arr16 = np.arange(60).reshape(12,5)
arr16

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [108]:
arr16[1:6,1:2][2][0] = 1000

In [109]:
arr16

array([[   0,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14],
       [  15, 1000,   17,   18,   19],
       [  20,   21,   22,   23,   24],
       [  25,   26,   27,   28,   29],
       [  30,   31,   32,   33,   34],
       [  35,   36,   37,   38,   39],
       [  40,   41,   42,   43,   44],
       [  45,   46,   47,   48,   49],
       [  50,   51,   52,   53,   54],
       [  55,   56,   57,   58,   59]])

In [110]:
##creating 3d array 

arr17 = np.random.randint(1,100,(3,4,5))          ##(tables,row,col)
arr17


array([[[39,  2, 73,  7, 82],
        [35, 45, 33, 84,  3],
        [38, 12, 85, 43, 66],
        [11, 87, 91, 62, 45]],

       [[80, 72, 68, 71, 18],
        [47, 56, 61,  7, 49],
        [ 8, 75, 37, 73, 54],
        [59, 64, 33, 94, 53]],

       [[86, 78, 55, 68, 91],
        [84, 54, 41,  1, 65],
        [53, 33, 16, 67, 56],
        [11, 80, 32, 90, 82]]])

In [111]:
arr18 = np.arange(225).reshape(5,15,3)
arr18

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [112]:
#3d access = [table start;end:skip,row,col]

arr18[1][2][2]

53

In [113]:
arr18[1:2,2:3,2:3][0][0][0] 

53

In [114]:
##
lst = [1,2,3,4,5]
# lst.reverse()

lst[::-1]






[5, 4, 3, 2, 1]

In [115]:
arr18[3][::-1]                       ##rows revesed 

array([[177, 178, 179],
       [174, 175, 176],
       [171, 172, 173],
       [168, 169, 170],
       [165, 166, 167],
       [162, 163, 164],
       [159, 160, 161],
       [156, 157, 158],
       [153, 154, 155],
       [150, 151, 152],
       [147, 148, 149],
       [144, 145, 146],
       [141, 142, 143],
       [138, 139, 140],
       [135, 136, 137]])

In [116]:
##rows and columns ek sath reverse 

arr18[3][::-1,::-1]

array([[179, 178, 177],
       [176, 175, 174],
       [173, 172, 171],
       [170, 169, 168],
       [167, 166, 165],
       [164, 163, 162],
       [161, 160, 159],
       [158, 157, 156],
       [155, 154, 153],
       [152, 151, 150],
       [149, 148, 147],
       [146, 145, 144],
       [143, 142, 141],
       [140, 139, 138],
       [137, 136, 135]])

In [117]:
arr16

array([[   0,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14],
       [  15, 1000,   17,   18,   19],
       [  20,   21,   22,   23,   24],
       [  25,   26,   27,   28,   29],
       [  30,   31,   32,   33,   34],
       [  35,   36,   37,   38,   39],
       [  40,   41,   42,   43,   44],
       [  45,   46,   47,   48,   49],
       [  50,   51,   52,   53,   54],
       [  55,   56,   57,   58,   59]])

In [125]:
np.min(arr16)
np.max(arr16)
np.mean(arr16)
np.median(arr16) 
np.sum(arr16) 
np.std(arr16) 

125.40237903112791

In [130]:
### sortinggg
arr19 = np.array([22,4444,222,5555])
arr20 = np.array([[2,3,48,1],[22,344,5,66]])

In [132]:
arr19.sort()
arr19[::-1]

array([5555, 4444,  222,   22])

In [134]:
arr20.sort()
arr20

array([[  1,   2,   3,  48],
       [  5,  22,  66, 344]])

In [137]:
##argsort

arr21 = np.array([7,5,2])
arr21

array([7, 5, 2])

In [138]:
np.argsort(arr21)

array([2, 1, 0], dtype=int64)

In [143]:
## arithmatical operations on array 

arr22 = np.array([1,2,3])
arr23 = np.array([4,5,7])
arr22 + arr23
arr22 - arr23
arr22 * arr23   

arr22 / arr23
arr22 + 2

array([3, 4, 5])

In [153]:
#concatenate

arr24 = np.array([1,2,3])
arr25 = np.array([4,5,8])
np.concatenate((arr24,arr25))

array([1, 2, 3, 4, 5, 8])

In [154]:
##vstack --vertical stack 

x = np.vstack((arr24,arr25))
x

array([[1, 2, 3],
       [4, 5, 8]])

In [155]:
##hstack --horizontal stack

y = np.hstack((arr24,arr25))
y

array([1, 2, 3, 4, 5, 8])

In [161]:
##split

arr26 = np.array([1,2,3,4,5,6])
# np.split(arr26,3)
np.split(arr26,2)

[array([1, 2, 3]), array([4, 5, 6])]

In [172]:
##vsplit 

arr27 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr27



array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [174]:
np.vsplit(arr27,3)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

In [ ]:
##hsplit


In [4]:
import numpy as np

# Create a 3D array (shape: 6x2x2)


# Split the array into 3 sub-arrays along axis 0


In [5]:
arr = np.arange(24).reshape(6, 2, 2)
print("Original 3D Array:\n", arr)

Original 3D Array:
 [[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]

 [[20 21]
  [22 23]]]


In [6]:
split_arr = np.split(arr, 3, axis=0)
# for i, sub_arr in enumerate(split_arr):
#     print(f"Sub-array {i}:\n{sub_arr}\n")
split_arr


[array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]]),
 array([[[ 8,  9],
         [10, 11]],
 
        [[12, 13],
         [14, 15]]]),
 array([[[16, 17],
         [18, 19]],
 
        [[20, 21],
         [22, 23]]])]